# ansible-playbook desktop.yml -i inv.yml -Kk
- hosts: desktop
  roles:
    - hostname
    - user
    - packages
    - aur
    # Configure Hyprland
    - compositor
    # Configure Desktop Utilities
    - shell
    - loginmanager
    # - launcher Wofi broken, not using
    - terminal