# Create aur user
- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

# Setup paru
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "~/repos/ext"
    state: directory
  become: yes
  become_user: aur_builder

- name: Clone paru
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: "~/repos/ext/paru"
    update: true
  become: yes
  become_user: aur_builder

- name: Build and install paru
  command:
    chdir: "~/repos/ext/paru"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/paru
  become: yes
  become_user: aur_builder