# Install packages
- name: Install desktop packages
  become: true
  ansible.builtin.package:
    name:
      - hyprland                # compositor
      - hyprpaper               # wallpaper manager
      - waybar                  # status bar
      - vscode
      - firefox
      - kitty
      - pamixer
    state: present




